version: "3.9"
services:
  angular:
    container_name: angular
    restart: always
    hostname: angular
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
  nest:
    container_name: nest
    hostname: nest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - "angular"