version: '3.8'

services:
  angularjs:
    container_name: angularjs
    hostname: angularjs
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200
    restart: always
#  nestjs:
#    container_name: nestjs
#    hostname: nestjs
#    build:
#      context: ./server
#      dockerfile: ./Dockerfile
#    ports:cd
#      - 5000:5000
#    restart: always