version: '3.8'

services:
  server:
    container_name: nestjs
    hostname: nestjs
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    restart: always